# Generated by Django 5.2.5 on 2025-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_adminsettings"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nodedocument",
            name="node_docume_node_id_b12040_idx",
        ),
        migrations.RemoveIndex(
            model_name="nodeusecasecandidate",
            name="node_usecas_node_id_e44084_idx",
        ),
        migrations.RemoveField(
            model_name="nodedocument",
            name="user",
        ),
        migrations.RemoveField(
            model_name="nodeusecasecandidate",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usecaseresearch",
            name="user",
        ),
        migrations.AddIndex(
            model_name="nodedocument",
            index=models.Index(fields=["node"], name="node_docume_node_id_3cc54b_idx"),
        ),
        migrations.AddIndex(
            model_name="nodeusecasecandidate",
            index=models.Index(fields=["node"], name="node_usecas_node_id_b3ba4e_idx"),
        ),
    ]
